Repository FRONT-END-BOOTCAMP-PLUS-5/TheHabit, pull requests merged in 2025-09, with the labels that each got.

#223 [Docs] readme.md 초안 작성
  README.md
Labels: 📄 Documentation

#231 Fix/issue#227 배포페이지에서 로그인 성공 이후 리다이렉트가 안되었던 이슈
  app/_components/tab-navigations/TabNavigation.tsx
  middleware.ts
  prisma/schema.prisma
Labels: ⚒️ Refactor, 🧪 Test

#229 [Refact] s3.service.ts의 환경변수명 변경
  backend/shared/services/s3.service.ts
Labels: 😵 Backend, ⚒️ Refactor

#232 Feat/issue#221 기존 undefined로 나왔던 피드백페이지 이름 수정, robots.ts + sitemap으로 SEO최적화 시도
  app/(anon)/_components/ChallengeList.tsx
  app/(anon)/_components/LoginCta.tsx
  app/(anon)/_components/UserProfileSection.tsx
  app/(anon)/feedback/_components/FeedBackBar.tsx
  app/(anon)/feedback/_components/FeedBackCurrentList.tsx
  app/(anon)/feedback/_components/FeedBackList.tsx
  app/(anon)/feedback/_components/FeedBackStatics.tsx
  app/(anon)/feedback/_components/FeedbackNav.tsx
  app/(anon)/feedback/page.tsx
  app/(anon)/layout.tsx
  app/(anon)/page.tsx
  app/(anon)/profile/_components/RoutineCompletion.tsx
  app/(anon)/profile/_components/UserProfile.tsx
  app/(anon)/profile/_components/UserProfileButton.tsx
  app/(anon)/profile/page.tsx
  app/_components/home/FeedBackHeader.tsx
  app/_components/home/HomePageList.tsx
  app/_components/layouts/Header.tsx
  app/_components/modals/FloatingModal.tsx
  app/_components/notifications/NotificationList.tsx
  app/_components/profile-images/ProfileImage.tsx
  app/_components/tab-navigations/TabNavigation.tsx
  app/_components/user-profile-section/UserProfileSection.tsx
  app/api/cron/routine-alerts/route.ts
  app/onboarding/_components/onBoardingStep.tsx
  app/onboarding/page.tsx
  app/page.tsx
  app/robots.ts
  app/sitemap.ts
  app/user/dashboard/[nickname]/page.tsx
  app/user/feedback/_components/FeedBackList.tsx
  backend/dashboards/application/usecases/GetDashboardByNicknameUsecase.ts
  middleware.ts
  prisma/schema.prisma
  public/consts/noneUserCategory.ts
  public/consts/tabItem.ts
  public/icons/login.svg
Labels: 🔧 Feature, ⚒️ Refactor

#246 [Refact] Feat/issue#245 GPT 모델로만 피드백 받았던 로직을 다른 Ai 모델들이 들어올 수 있도록 수정
  app/_components/home/FeedBackHeader.tsx
  app/_components/notifications/NotificationSettings.tsx
  app/api/ai/route.ts
  app/api/feedback/[nickname]/[id]/route.ts
  app/api/feedback/[nickname]/route.ts
  app/api/gpt/route.ts
  app/user/feedback/[nickname]/[id]/_components/FeedBackById.tsx
  app/user/feedback/_components/AiProvider.ts
  app/user/feedback/_components/FeedBackPostData.ts
  app/user/feedback/_components/ValidateFeedBacAiResponse.ts
  backend/ai/application/dtos/AiRequestDto.ts
  backend/ai/application/usecases/AddAiResponseUsecase.ts
  backend/ai/domain/entities/AiEntity.ts
  backend/ai/domain/repositories/IAiRepository.ts
  backend/ai/infrastructure/repositories/AiRepository.ts
  backend/dashboards/infrastructure/repository/PrDashboardRepository.ts
  backend/feedbacks/application/dtos/AddfeedbackDto.ts
  backend/feedbacks/application/dtos/FeedbackDto.ts
  backend/feedbacks/domain/entities/FeedBackEntity.ts
  backend/feedbacks/infrastructure/repositories/PrFeedBackRepository.ts
  backend/gpt/application/dtos/GPTRequestDto.ts
  backend/gpt/application/usecases/AddGPTResponseUsecase.ts
  backend/gpt/domain/entities/GPTEntity.ts
  backend/gpt/domain/repositories/IGPTRepository.ts
  backend/gpt/infrastructure/repositories/GPTRepository.ts
  backend/shared/services/s3.service.ts
  libs/api/ai.api.ts
  libs/api/feedback.api.ts
  libs/api/gpt.api.ts
  libs/hooks/ai-hooks/useGetAiResponse.ts
  libs/hooks/feedback-hooks/useCreateFeedBack.ts
  libs/hooks/feedback-hooks/useGetFeedBackById.ts
  libs/hooks/gpt-hooks/useGetGptResponse.ts
  public/consts/AIPrompt.ts
  public/consts/AiModel.ts
  public/consts/AiProvider.ts
  public/consts/gptPrompt.ts
Labels: 😵 Backend, ⚒️ Refactor, 📞 API
