Repository FRONT-END-BOOTCAMP-PLUS-5/TheHabit, pull requests merged in 2025-08, with the labels that each got.

#5 [Feat] 프로젝트 초기설정 - Issue#1
  .gitmessage
  .husky/commit-msg
  README.md
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/manifest.ts
  backend/auths/applications/dtos/.gitkeep
  backend/auths/applications/usecases/.gitkeep
  backend/auths/domains/entities/.gitkeep
  backend/auths/domains/repositories/.gitkeep
  backend/auths/infrastructures/mappers/.gitkeep
  backend/auths/infrastructures/repositories/.gitkeep
  backend/challenges/applications/dtos/.gitkeep
  backend/challenges/applications/usecases/.gitkeep
  backend/challenges/domains/entities/.gitkeep
  backend/challenges/domains/repositories/.gitkeep
  backend/challenges/infrastructures/mappers/.gitkeep
  backend/challenges/infrastructures/repositories/.gitkeep
  backend/feedbacks/applications/dtos/.gitkeep
  backend/feedbacks/applications/usecases/.gitkeep
  backend/feedbacks/domains/entities/.gitkeep
  backend/feedbacks/domains/repositories/.gitkeep
  backend/feedbacks/infrastructures/mappers/.gitkeep
  backend/feedbacks/infrastructures/repositories/.gitkeep
  backend/routines/applications/dtos/.gitkeep
  backend/routines/applications/usecases/.gitkeep
  backend/routines/domains/entities/.gitkeep
  backend/routines/domains/repositories/.gitkeep
  backend/routines/infrastructures/mappers/.gitkeep
  backend/routines/infrastructures/repositories/.gitkeep
  backend/users/applications/dtos/.gitkeep
  backend/users/applications/usecases/.gitkeep
  backend/users/domains/entities/.gitkeep
  backend/users/domains/entities/UserProfile.ts
  backend/users/domains/repositories/.gitkeep
  backend/users/infrastructures/mappers/.gitkeep
  backend/users/infrastructures/repositories/.gitkeep
  bun.lock
  next.config.ts
  package.json
  public/images/icons/apple-touch-icon.png
  public/images/icons/manifest-192x192.png
  public/images/icons/manifest-512x512.png
  public/sw.js
  public/workbox-1bb06f5e.js
  tsconfig.json
Labels: 📄 Documentation, 😵 Backend, 🔧 Feature, 🖥️ Frontend, ⚙️ Settings

#11 Fix: tsconfig.ts 에러 수정
  next.config.ts
  package.json
Labels: 🐛 Bug

#13 docs : .gitmessage -> .gitmessage.txt로 수정, 공통 컴포넌트 components 폴더 생성
  .gitmessage.txt
  app/_components/Button/Button.tsx
  app/_components/Input/Input.tsx
  app/_components/ProfileImage/ProfileImage.tsx
  app/_components/TabNavigation/TabNavigation.tsx
  package.json
Labels: 📄 Documentation

#17 input components 추가
  app/_components/Input/Input.tsx
  app/_components/Input/Password.tsx
  app/page.tsx
Labels: 🔧 Feature, 🖥️ Frontend, 🎨 Publishing

#21 Issue#6 TabNavBar UI 제작 완료
  app/_components/Button/Button.tsx
  app/_components/Input/Input.tsx
  app/_components/TabNavigation/TabNavigation.tsx
  app/feedback/layout.tsx
  app/feedback/page.tsx
  app/globals.css
  bun.lock
  package.json
  prisma/schema.prisma
  public/consts/tabItem.ts
  public/icons/activeAlarm.svg
  public/icons/activeHome.svg
  public/icons/activeSearch.svg
  public/icons/activeSetting.svg
  public/icons/alarm.svg
  public/icons/apple-touch-icon.png
  public/icons/home.svg
  public/icons/manifest-192x192.png
  public/icons/manifest-512x512.png
  public/icons/search.svg
  public/icons/setting.svg
  public/icons/tabButton.svg
Labels: 🔧 Feature, 🎨 Publishing

#27 [Feat] 챌린지 backend
  backend/challenges/applications/usecases/.gitkeep
  backend/challenges/applications/usecases/AddChallengeUsecase.ts
  backend/challenges/applications/usecases/DeleteChallengeUsecase.ts
  backend/challenges/applications/usecases/GetAllChallengesUsecase.ts
  backend/challenges/applications/usecases/GetChallengeByIdUsecase.ts
  backend/challenges/applications/usecases/GetChallengeUsecase.ts
  backend/challenges/applications/usecases/GetChallengesByCategoryUsecase.ts
  backend/challenges/applications/usecases/GetChallengesByUserUsecase.ts
  backend/challenges/applications/usecases/UpdateChallengeUsecase.ts
  backend/challenges/domains/entities/.gitkeep
  backend/challenges/domains/entities/ChallengeEntity.ts
  backend/challenges/domains/repositories/.gitkeep
  backend/challenges/domains/repositories/IChallengeRepository.ts
  backend/challenges/infrastructures/repositories/.gitkeep
  backend/challenges/infrastructures/repositories/PrChallengeRepository.ts
  bun.lock
  public/utils/prismaClient.ts
  test/PrChallengeRepositoryTest.ts
Labels: 😵 Backend, 🔧 Feature, 🧪 Test

#33 Issue#7
  backend/routine-completions/domains/entities/routine-completion/routineCompletion.ts
Labels: 🐛 Bug, 😵 Backend, ⚒️ Refactor

#38 [FEAT] Git Action CI/CD 기능 구현
  .github/workflows/depoly.yml
Labels: ⚙️ Settings

#19 Issue#4 로그인 기능 구현
  app/_components/Input/Input.tsx
  app/api/auth/[...nextauth]/auth.ts
  app/api/auth/[...nextauth]/route.ts
  app/auth/components/LoginFormClient.tsx
  app/auth/components/NextAuthSessionProvider.tsx
  app/auth/components/Notification.tsx
  app/auth/page.tsx
  app/signup/components/AccountSection.tsx
  app/signup/components/AgreementSection.tsx
  app/signup/components/CheckBox.tsx
  app/signup/components/ProfileSection.tsx
  app/signup/components/SignUpFormClient.tsx
  app/signup/page.tsx
  bun.lock
  package.json
  tsconfig.json
Labels: 🔧 Feature, 🖥️ Frontend, 📞 API

#46 템플릿 리터럴을 사용한 메소드인 $queryRaw에 alias 사용 + dto + CreateUserUsecase 생성
  backend/users/applications/dtos/UserDto.ts
  backend/users/applications/usecases/CreateUserUsecase.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  public/fileEdit.png
  test/PrChallengeRepositoryTest.ts
Labels: 😵 Backend, ⚒️ Refactor

#49 [Feat] Challenges API route 구현
  app/api/challenges/[id]/route.ts
  app/api/challenges/categories/[categoryId]/route.ts
  app/api/challenges/route.ts
  app/challenges/page.tsx
  backend/challenges/applications/dtos/.gitkeep
  backend/challenges/applications/dtos/AddChallengeDto.ts
  backend/challenges/applications/dtos/ChallengeDto.ts
  backend/challenges/applications/usecases/AddChallengeUsecase.ts
  backend/challenges/domains/entities/ChallengeEntity.ts
  backend/challenges/infrastructures/mappers/.gitkeep
  backend/challenges/infrastructures/mappers/AddChallengeDataMapper.ts
  backend/challenges/infrastructures/mappers/ChallengeDataMapper.ts
  backend/challenges/infrastructures/repositories/PrChallengeRepository.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  libs/axios/axiosInstance.ts
  prisma/schema.prisma
  public/sw.js
Labels: 😵 Backend, 🔧 Feature, 🧪 Test

#54 PrUserRepository.ts 수정으로 다시 원복
  backend/users/infrastructures/repositories/PrUserRepository.ts
Labels: 😵 Backend, 📞 API

#69 [temp/feat] 메인 페이지 UI 구현중
  app/_components/challenges-accordion/ChallengesAccordion.tsx
  app/_components/layouts/Header.tsx
  app/_components/profile-images/ProfileImage.tsx
  app/_components/user-profile-section/UserProfileSection.tsx
  app/_components/weekly-slides/DayCard.tsx
  app/_components/weekly-slides/WeeklySlide.tsx
  app/api/challenges/[id]/route.ts
  app/api/challenges/categories/[categoryId]/route.ts
  app/api/challenges/route.ts
  app/globals.css
  app/layout.tsx
  app/main/_components/ChallengeListSection.tsx
  app/main/page.tsx
  backend/challenges/applications/usecases/AddChallengeUsecase.ts
  backend/challenges/applications/usecases/DeleteChallengeUsecase.ts
  backend/challenges/applications/usecases/GetAllChallengesUsecase.ts
  backend/challenges/applications/usecases/GetChallengeByIdUsecase.ts
  backend/challenges/applications/usecases/GetChallengeUsecase.ts
  backend/challenges/applications/usecases/GetChallengesByCategoryUsecase.ts
  backend/challenges/applications/usecases/GetChallengesByUserUsecase.ts
  backend/challenges/applications/usecases/UpdateChallengeUsecase.ts
  backend/challenges/domains/entities/Challenge.ts
  backend/challenges/domains/repositories/IChallengeRepository.ts
  backend/challenges/infrastructures/repositories/PrChallengeRepository.ts
  middleware.ts
  next.config.ts
  public/fonts/font.ts
  public/icons/icon_down_arrow.svg
  public/icons/icon_up_arrow.png
  public/utils/dateUtils.ts
  test/PrChallengeRepositoryTest.ts
Labels: 🔧 Feature, 🖥️ Frontend, 🎨 Publishing

#75 AWS S3 프로필 이미지 업데이트 + 에디터 페이지 백엔드, 프론트, 기능 완료
  app/_components/profile-images/ProfileImage.tsx
  app/api/users/[id]/route.ts
  app/api/users/edit/nickname/[id]/route.ts
  app/api/users/edit/profile/[id]/route.ts
  app/api/users/edit/username/[id]/route.ts
  app/user/follow/components/List.tsx
  app/user/follow/page.tsx
  app/user/profile/[nickname]/page.tsx
  app/user/profile/edit/[nickname]/page.tsx
  app/user/profile/edit/components/Back.tsx
  app/user/profile/edit/components/Name.tsx
  app/user/profile/edit/components/Nickname.tsx
  backend/follows/applications/dtos/FollowerDto.ts
  backend/follows/applications/dtos/FollowingDto.ts
  backend/follows/domains/entities/FollowEntity.ts
  backend/follows/infrastructures/repositories/PrFollowRepository.ts
  backend/users/applications/dtos/UserDto.ts
  backend/users/applications/usecases/DeleteUserUsecase.ts
  backend/users/applications/usecases/UpdateUserNameUsecase.ts
  backend/users/applications/usecases/UpdateUserNicknameUsecase.ts
  backend/users/applications/usecases/UpdateUserProfileImgUsecase.ts
  backend/users/applications/usecases/UpdateUserUsecase.ts
  backend/users/domains/entities/UserEntity.ts
  backend/users/domains/repositories/IUserRepository.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  bun.lock
  libs/api/users.api.ts
  next.config.ts
  package.json
  prisma/schema.prisma
Labels: 😵 Backend, 🖥️ Frontend, 📞 API

#83 [Feat] Issue#78 회원가입 Backend 구현
  app/api/signup/route.ts
  app/signup/components/ProfileSection.tsx
  app/signup/components/SignupForm.tsx
  backend/auths/applications/usecases/CreateUserUsecase.ts
  backend/users/domains/repositories/IUserRepository.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  libs/hooks/signup/useSignUp.ts
  prisma/schema.prisma
  public/consts/Rex.ts
  public/consts/loginItem.ts
  public/consts/loginItme.ts
  public/consts/signupItem.ts
Labels: 😵 Backend, 🔧 Feature, ⚒️ Refactor, 📞 API

#93 Fix/issue#92 - dev브랜치 머지 후 컨플릭트 수정
  app/_components/buttons/Button.tsx
  app/_components/layouts/Header.tsx
  backend/auths/applications/usecases/LoginUsecase.ts
  backend/users/domains/repositories/IUserRepository.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  bun.lock
  package-lock.json
Labels: 🐛 Bug, ⚒️ Refactor

#95 Feat/issue#87 - 플로팅 공통 모달 UI 구현
  .prettierignore
  .prettierrc.json
  app/_components/challenges-accordion/ChallengesAccordion.tsx
  app/_components/modals/FloatingModal.tsx
  app/_components/profile-images/ProfileImage.tsx
  app/_components/providers/ModalProvider.tsx
  app/main/_components/AddChallengeButton.tsx
  app/main/_components/AllChallengeList.tsx
  app/main/_components/CategoryChallengeList.tsx
  app/main/_components/ChallengeListSection.tsx
  app/main/page.tsx
  app/user/dashboard/_components/ChallengeListSection.tsx
  libs/hooks/useModal.ts
  libs/stores/modalStore.ts
  public/file.svg
  public/globe.svg
  public/icons/activeAlarm.svg
  public/icons/activeHome.svg
  public/icons/activeSearch.svg
  public/icons/activeSetting.svg
  public/icons/alarm.svg
  public/icons/back.svg
  public/icons/camera.svg
  public/icons/fileUpload.svg
  public/icons/google.svg
  public/icons/googleIcon.svg
  public/icons/home.svg
  public/icons/icon_close.svg
  public/icons/icon_down_arrow.svg
  public/icons/icon_study.svg
  public/icons/kakao.svg
  public/icons/noShowPassword.svg
  public/icons/search.svg
  public/icons/setting.svg
  public/icons/showPassword.svg
  public/icons/tabButton.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
Labels: 🔧 Feature, ⚒️ Refactor, 🖥️ Frontend, 🎨 Publishing

#97 hotfix : bcrypt.js 재적용, 로그인 이슈 해결
  app/_components/challenges-accordion/ChallengesAccordion.tsx
  app/_components/checkboxes/Checkbox.tsx
  app/_components/file-upload/FileUpload.tsx
  app/_components/inputs/Input.tsx
  app/_components/layouts/Header.tsx
  app/_components/loading/LoadingSpinner.tsx
  app/_components/modals/FloatingModal.tsx
  app/_components/profile-images/ProfileImage.tsx
  app/_components/providers/ModalProvider.tsx
  app/_components/routine-accordion/ErrorBoundary.tsx
  app/_components/routine-accordion/RoutineAccordionContent.tsx
  app/_components/routine-accordion/RoutineCompletionModal.tsx
  app/_components/routine-accordion/RoutineItem.tsx
  app/_components/routine-accordion/RoutineListSkeleton.tsx
  app/_components/skeleton/Skeleton.tsx
  app/api/routine-completions/[id]/route.ts
  app/api/routine-completions/route.ts
  app/api/routines/route.ts
  app/globals.css
  app/user/dashboard/_components/ChallengeListSection.tsx
  backend/auths/applications/usecases/LoginUsecase.ts
  backend/challenges/applications/usecases/GetChallengesByCategoryUsecase.ts
  backend/challenges/applications/usecases/UpdateChallengeUsecase.ts
  backend/challenges/domains/entities/Challenge.ts
  backend/routine-completions/applications/dtos/RoutineCompletionDto.ts
  backend/routine-completions/applications/usecases/AddRoutineCompletionUseCase.ts
  backend/routine-completions/applications/usecases/CreateRoutineCompletionUseCase.ts
  backend/routine-completions/applications/usecases/DeleteRoutineCompletionUseCase.ts
  backend/routine-completions/applications/usecases/UpdateRoutineCompletionUseCase.ts
  backend/routines/applications/dtos/RoutineDto.ts
  backend/routines/domains/entities/routine.ts
  backend/shared/types/ApiResponse.ts
  libs/api/routine-completions.api.ts
  libs/api/routines.api.ts
  libs/hooks/routine-completions-hooks/useCreateRoutineCompletion.ts
  libs/hooks/routine-completions-hooks/useDeleteRoutineCompletion.ts
  libs/hooks/routine-completions-hooks/useGetRoutineCompletionsByChallenge.ts
  libs/hooks/routines-hooks/useCreateRoutine.ts
  libs/hooks/routines-hooks/useDeleteRoutine.ts
  libs/hooks/routines-hooks/useGetDashboardRoutines.ts
  libs/hooks/routines-hooks/useGetRoutinesByChallenge.ts
  libs/hooks/routines-hooks/useRoutineCompletion.ts
  libs/hooks/routines-hooks/useUpdateRoutine.ts
  libs/stores/modalStore.ts
Labels: 🐛 Bug, 😵 Backend, ⚒️ Refactor

#114 bug/issue#112 - 누락된 두 개의 메서드 추가
  backend/users/domains/repositories/IUserRepository.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  prisma/schema.prisma
Labels: 🐛 Bug, 😵 Backend

#108 [refact] Refact/issue#105 - 에디터 페이지 이름변경, 닉네임변경시 속도개선 + 로그인유저 api info 커스텀훅 적용
  app/_components/none/None.tsx
  app/user/profile/components/Button.tsx
  app/user/profile/components/Completion.tsx
  app/user/profile/edit/[nickname]/page.tsx
  app/user/profile/edit/components/Name.tsx
  app/user/profile/edit/components/Nickname.tsx
  backend/users/infrastructures/repositories/PrUserRepository.ts
  libs/hooks/user-hooks/useGetUserCompletion.ts
  libs/hooks/user-hooks/useGetUserInfo.ts
  prisma/schema.prisma
  public/consts/userRoutineCompletionsBtn.ts
  public/consts/userRoutineCompletionsBtnColor.ts
Labels: ⚒️ Refactor

#120 Hotfix/issue#119 - #112번 적용되지 않은 이슈 관련 핫픽스
  backend/users/domains/repositories/IUserRepository.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
Labels: 🐛 Bug, 😵 Backend

#118 [bug] 중복 reviews 삭제
  prisma/schema.prisma
Labels: 🐛 Bug

#141 Feat/issue#140 피드백 api 수정했습니다
  app/(onboarding)/_components/onBoardingStep.tsx
  app/api/feedback/[id]/route.ts
  app/api/feedback/route.ts
  app/api/routines/[id]/complete/route.ts
  app/user/feedback/[id]/_component/FeedBackById.tsx
  app/user/feedback/_components/FeedBackDetail.tsx
  app/user/feedback/_components/FeedBackPostData.ts
  app/user/feedback/_components/ValidateFeedBackGPTResponse.ts
  backend/feedbacks/applications/dtos/AddfeedbackDto.ts
  backend/gpt/applications/dtos/GPTRequestDto.ts
  libs/api/gpt.api.ts
  package-lock.json
  public/consts/onboarding.ts
Labels: 😵 Backend, ⚒️ Refactor, 📞 API

#149 Fix/issue#139 카카오 로그인
  app/api/auth/[...nextauth]/auth.ts
  backend/auths/applications/usecases/KakaoLoginUsecase.ts
Labels: 😵 Backend

#151 feat: 로그아웃 버튼 추가
  app/user/profile/edit/[nickname]/page.tsx
  app/user/profile/edit/_components/Back.tsx
  app/user/profile/edit/_components/LogOut.tsx
  app/user/profile/edit/_components/Name.tsx
  app/user/profile/edit/_components/Nickname.tsx
Labels: 🔧 Feature, 🖥️ Frontend

#159 Hotfix/issue#158 - <div> 닫는 태그 누락 & import 경로 이슈 해결
  app/page.tsx
  app/user/profile/edit/[nickname]/page.tsx
Labels: 🐛 Bug, ⚒️ Refactor, 🖥️ Frontend

#171 Feat/issue#163 - 컨펌 모달 추가
  app/_components/buttons/Button.tsx
  app/_components/error-boundary/DataLoadingErrorBoundary.tsx
  app/_components/error-boundary/SimpleErrorBoundary.tsx
  app/_components/file-upload/FileUpload.tsx
  app/_components/modals/ConfirmModal.tsx
  app/_components/providers/ToastProvider.tsx
  app/_components/routine-accordion/RoutineCompletionModal.tsx
  app/_components/routine-accordion/RoutineItem.tsx
  app/_components/toasts/Toast.tsx
  app/_components/user-profile-section/UserProfileSection.tsx
  app/globals.css
  app/layout.tsx
  app/user/dashboard/_components/AddChallengeForm.tsx
  app/user/dashboard/_components/ChallengeListSection.tsx
  app/user/follow/components/List.tsx
  app/user/profile/[nickname]/page.tsx
  app/user/profile/edit/[nickname]/page.tsx
  docs/error-boundary-guide.md
Labels: 🔧 Feature, 🖥️ Frontend, 🎨 Publishing

#160 Feat/issue#144 - 대시보드 에러 바운더리 처리
  app/_components/user-profile-section/UserProfileSection.tsx
Labels: 📄 Documentation, 🔧 Feature, 🖥️ Frontend

#176 [Refact / Feat] API 동적 라우트 문제 해결, 프로필 섹션 해결, 루틴 아코디언 컨텐츠 구현 완료
  app/_components/challenges-accordion/ChallengesAccordion.tsx
  app/_components/challenges-accordion/ChallengesAccordionContent.tsx
  app/_components/challenges-accordion/RoutineCompletionForm.tsx
  app/_components/file-upload/FileUpload.tsx
  app/_components/routine-accordion/RoutineAccordionContent.tsx
  app/_components/routine-accordion/RoutineCompletionModal.tsx
  app/_components/user-profile-section/UserProfileSection.tsx
  app/api/friends/follower/[id]/route.ts
  app/api/friends/following/[id]/route.ts
  app/api/routine-completions/route.ts
  app/api/users/[nickname]/route.ts
  app/api/users/edit/[userNickname]/route.ts
  app/api/users/profile/[userNickname]/route.ts
  app/api/users/review/[userNickname]/route.ts
  app/api/users/routine/[userNickname]/route.ts
  app/user/dashboard/[nickname]/page.tsx
  app/user/dashboard/_components/AddChallengeForm.tsx
  app/user/dashboard/_components/AddRoutineForm.tsx
  app/user/dashboard/_components/AllChallengeList.tsx
  app/user/dashboard/_components/CategoryChallengeList.tsx
  app/user/dashboard/_components/ChallengeListSection.tsx
  app/user/profile/components/UserPage.tsx
  app/user/profile/edit/[nickname]/page.tsx
  app/user/profile/edit/_components/Nickname.tsx
  backend/routine-completions/applications/usecases/AddRoutineCompletionUseCase.ts
  backend/routines/applications/dtos/RoutineDto.ts
  backend/users/applications/dtos/UserProfileDto.ts
  backend/users/applications/dtos/UserProfileDtoMapper.ts
  backend/users/applications/usecases/GetUserUsecase.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  libs/api/dashboards.api.ts
  libs/api/follows.api.ts
  libs/api/routine-completions.api.ts
  libs/api/routines.api.ts
  libs/api/users.api.ts
  libs/hooks/challenges-hooks/useCreateChallenge.ts
  libs/hooks/index.ts
  libs/hooks/routine-completions-hooks/useCreateRoutineCompletion.ts
  libs/hooks/routines-hooks/index.ts
  libs/hooks/routines-hooks/useCreateRoutine.ts
  libs/hooks/routines-hooks/useGetAllRoutines.ts
  libs/hooks/routines-hooks/useGetRoutinesByNickname.ts
  libs/hooks/user-hooks/useGetUserByNickname.ts
  libs/hooks/user-hooks/useGetUserCompletion.ts
Labels: 🐛 Bug, 😵 Backend, 🔧 Feature, ⚒️ Refactor, 🖥️ Frontend, 📞 API

#170 Fix/issue#165 회원가입 체크박스 PR 코멘트 수정
  app/_components/inputs/CustomInput.tsx
  app/_components/tab-navigations/TabNavigation.tsx
  app/api/auth/[...nextauth]/auth.ts
  app/layout.tsx
  app/login/_components/LoginForm.tsx
  app/login/_components/SocialLogin.tsx
  app/login/page.tsx
  app/page.tsx
  app/signup/components/ProfileSection.tsx
  app/signup/components/SignUpTitle.tsx
  app/signup/components/SignupForm.tsx
  app/signup/page.tsx
  backend/auths/applications/usecases/CreateUserUsecase.ts
  backend/auths/applications/usecases/GoogleLoginUsecase.ts
  backend/auths/applications/usecases/KakaoLoginUsecase.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  package-lock.json
  public/consts/checkBoxItem.ts
  public/consts/signupItem.ts
  public/consts/tabItem.ts
  public/icons/activeAlarm.svg
  public/icons/activeFeedback.svg
  public/icons/activeProfile.svg
  public/icons/activeSearch.svg
  public/icons/activeSetting.svg
  public/icons/eye.svg
  public/icons/eye_off.svg
  public/icons/feedback.svg
  public/icons/home.svg
  public/icons/profile.svg
Labels: ⚒️ Refactor, 🖥️ Frontend

#192 Feat/issue#190 피드백 날짜 수정 + confirm 모달창 수정
  app/_components/home/FeedBackHeader.tsx
  app/_components/home/HomePageList.tsx
  app/_components/layouts/Header.tsx
  app/_components/modals/ConfirmModal.tsx
  app/_components/providers/LayoutProvider.tsx
  app/_components/providers/QueryProvider.tsx
  app/layout.tsx
  app/login/feedback/_components/FeedBackDetail.tsx
  app/onboarding/_components/onBoardingStep.tsx
  app/page.tsx
  app/user/feedback/[nickname]/[id]/_components/FeedBackById.tsx
  app/user/feedback/[nickname]/layout.tsx
  app/user/feedback/_components/CalcFeedBackData.ts
  app/user/feedback/_components/FeedBackList.tsx
  app/user/feedback/_components/FeedBackStatistics.tsx
  libs/hooks/feedback-hooks/useCreateFeedBack.ts
  middleware.ts
  public/consts/routeName.ts
  public/utils/layoutRoute.ts
Labels: 🖥️ Frontend, 🎨 Publishing

#194 refact : 피드백 버튼 disabled 처리
  app/_components/modals/ConfirmModal.tsx
  app/user/feedback/_components/CalcFeedBackData.ts
  app/user/feedback/_components/FeedBackDetail.tsx
  app/user/feedback/_components/FeedBackStatistics.tsx
Labels: ⚒️ Refactor, 🎨 Publishing

#195 Feat/Issue#157 PWA 알림 시스템 구현
  app/_components/notifications/NotificationList.tsx
  app/_components/notifications/NotificationSettings.tsx
  app/api/friends/following/[id]/route.ts
  app/api/notifications/check-subscription/route.ts
  app/api/notifications/subscribe/route.ts
  app/api/notifications/unsubscribe/route.ts
  app/notifications/page.tsx
  backend/notifications/applications/dtos/PushSubscriptionDto.ts
  backend/notifications/applications/usecases/SendPushNotificationUseCase.ts
  backend/notifications/applications/usecases/SubscribePushNotificationUseCase.ts
  backend/notifications/applications/usecases/UnsubscribePushNotificationUseCase.ts
  backend/notifications/domains/entities/PushSubscription.ts
  backend/notifications/domains/repositories/IPushSubscriptionRepository.ts
  backend/notifications/domains/services/IPushNotificationService.ts
  backend/notifications/infrastructures/repositories/PrPushSubscriptionRepository.ts
  backend/notifications/infrastructures/services/WebPushNotificationService.ts
  backend/routines/applications/usecases/AddRoutineUseCase.ts
  libs/api/notifications.api.ts
  libs/hooks/notifications-hooks/index.ts
  libs/hooks/notifications-hooks/usePushSubscription.ts
  next.config.ts
  package.json
  prisma/schema.prisma
  public/images/icons/badge-icon.png
  public/images/icons/manifest-192x192.png
  public/images/icons/notification-icon.png
  public/push-sw.js
  public/sw.js
  public/test-notification.html
  public/workbox-1bb06f5e.js
Labels: 😵 Backend, 🖥️ Frontend, 📞 API

#200 [feat] 승민님을 위해서 카멜케이스에서 스네이크 케이스로 복귀 제하하하하하하하feat] 승민님을 위해서 카멜케이스에서 스네이크 케이스로 복귀 제하하하하하하하
  prisma/schema.prisma
Labels: 😵 Backend

#209 Feat/issue#203 텝 네브바 수정했습니다
  app/_components/home/FeedBackHeader.tsx
  app/_components/providers/LayoutProvider.tsx
  app/_components/tab-navigations/TabNavigation.tsx
  app/layout.tsx
  app/user/feedback/[nickname]/layout.tsx
  app/user/feedback/_components/FeedBackList.tsx
  backend/challenges/infrastructures/repositories/PrChallengeRepository.ts
  prisma/schema.prisma
  public/consts/tabItem.ts
Labels: 🐛 Bug, ⚒️ Refactor, 🎨 Publishing

#202 Feat/issue#196 알림 페이지 및 알림 시스템 구현
  app/api/friends/following/[id]/route.ts
  app/api/notifications/[id]/route.ts
  app/api/notifications/route.ts
  app/api/routine-completions/route.ts
  app/user/notifications/_components/NotificationItem.tsx
  app/user/notifications/_components/NotificationList.tsx
  app/user/notifications/_components/PushSubscriptionToggle.tsx
  app/user/notifications/page.tsx
  backend/notifications/applications/usecases/CreateNotificationUsecase.ts
  backend/notifications/applications/usecases/GetNotificationsByUserIdUsecase.ts
  backend/notifications/applications/usecases/MarkAllNotificationsAsReadUsecase.ts
  backend/notifications/applications/usecases/MarkNotificationAsReadUsecase.ts
  backend/notifications/domains/entities/Notification.ts
  backend/notifications/domains/repositories/INotificationRepository.ts
  backend/notifications/infrastructures/repositories/PrNotificationRepository.ts
  package.json
  prisma/schema.prisma
Labels: 😵 Backend, 🔧 Feature, 🖥️ Frontend, 📞 API

#215 Feat/issue#203 피드백 버튼 추가
  app/_components/challenges-accordion/ChallengesAccordion.tsx
  app/_components/challenges-accordion/ChallengesAccordionContent.tsx
  app/user/dashboard/_components/CategoryChallengeList.tsx
  backend/challenges/infrastructures/repositories/PrChallengeRepository.ts
  backend/notifications/infrastructures/services/WebPushNotificationService.ts
  prisma/schema.prisma
Labels: 🔧 Feature, 🖥️ Frontend

#219 Fix/issue#213 구글 로그인 리다이렉트 무한 루프 해결
  app/_components/user-profile-section/UserProfileSection.tsx
  app/api/auth/[...nextauth]/auth.ts
  app/login/_components/LoginForm.tsx
  app/login/_components/SocialLogin.tsx
  app/onboarding/_components/onBoardingStep.tsx
  app/signup/components/ProfileSection.tsx
  app/signup/components/SignUpTitle.tsx
  app/signup/components/SignupForm.tsx
  app/signup/page.tsx
  app/user/dashboard/[nickname]/page.tsx
  app/user/dashboard/page.tsx
  app/user/profile/edit/[nickname]/page.tsx
  backend/auths/applications/dtos/LoginResponseDto.ts
  backend/auths/applications/usecases/GoogleLoginUsecase.ts
  backend/auths/applications/usecases/KakaoLoginUsecase.ts
  backend/auths/applications/usecases/LoginUsecase.ts
  backend/users/infrastructures/repositories/PrUserRepository.ts
  middleware.ts
  next-auth.d.ts
  public/consts/signupItem.ts
  public/consts/tabItem.ts
  public/utils/routeUtils.ts
Labels: 🐛 Bug, 😵 Backend, 🖥️ Frontend
